SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrdenesProduccion](
	[C2_FILIAL] [varchar](2) NULL,
	[C2_NUM] [varchar](20) NOT NULL,
	[C2_PRODUTO] [varchar](20) NULL,
	[C2_QUANT] [decimal](18, 4) NULL,
	[C2_QUJE] [decimal](18, 4) NULL,
	[C2_EMISSAO] [date] NULL,
	[C2_DATPRF] [date] NULL,
	[C2_CC] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[C2_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
