"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const products_controller_js_1 = require("../../controllers/controllers_scada/products.controller.js");
const router = (0, express_1.Router)();
router.get("/products", products_controller_js_1.getProducts);
router.post("/products", products_controller_js_1.createNewProduct);
router.get("/products/count", products_controller_js_1.getTotalProducts);
router.get("/products/:id", products_controller_js_1.getProductById);
router.delete("/products/:id", products_controller_js_1.deleteProductById);
router.put("/products/:id", products_controller_js_1.updateProductById);
exports.default = router;
